"""add media_folder table and folder_id columns

Revision ID: 9601ef6da2e2
Revises: n9i0j1k2l3m4
Create Date: 2026-06-09 18:53:04.728316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9601ef6da2e2'
down_revision = 'n9i0j1k2l3m4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'media_type', name='uq_media_folder_path_media_type')
    )
    with op.batch_alter_table('media_folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_folder_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_folder_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_image_folder_id_media_folder', 'media_folder', ['folder_id'], ['id'])

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_video_folder_id_media_folder', 'media_folder', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('fk_video_folder_id_media_folder', type_='foreignkey')
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_folder_id_media_folder', type_='foreignkey')
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('media_folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_folder_uuid'))
        batch_op.drop_index(batch_op.f('ix_media_folder_path'))

    op.drop_table('media_folder')
    # ### end Alembic commands ###
